addSbtPlugin("com.github.gseitz"    % "sbt-release"           % "1.0.3")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"               % "1.0.0")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"          % "1.1")
addSbtPlugin("org.scalastyle"      %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "1.2.0")
addSbtPlugin("pl.project13.scala"   % "sbt-jmh"               % "0.2.11")
addSbtPlugin("org.scalariform"      % "sbt-scalariform"       % "1.6.0")
addSbtPlugin("io.get-coursier"      % "sbt-coursier"          % "1.0.0-M14-2")
